### ISSUE TITLE
ERR_MODULE_NOT_FOUND when imported in an mjs file

### ISSUE THREAD

**Issue by meglio** [gajus/fast-printf#4]
In my `mjs` file:

```
import {printf} from "fast-printf";
```

Error thrown in console:

`Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/xxx/node_modules/.pnpm/fast-printf@1.6.3/node_modules/fast-printf/dist/esm/src/createPrintf' imported from /xxx/node_modules/.pnpm/fast-printf@1.6.3/node_modules/fast-printf/dist/esm/src/printf.js`

(replaced full path prefix with `xxx` for readability).

Is this related to the library, or am I using node in a wrong way? Please advise.
--- Many thanks, Anton

**Comment by meglio** [comment]
Please check if [this node documentation](https://nodejs.org/api/esm.html#esm_import_specifiers) is relevant:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/282177/110556617-cf687280-818e-11eb-9999-91dd3f9a770e.png">

Whereas in your `printf.js` it says:

```
import { createPrintf, } from './createPrintf';
export { createPrintf, };
export const printf = createPrintf();

```

(no file extension specified)

**Comment by MrJYJ** [comment]
SyntaxError: Invalid regular expression: /(?:%(?<flag>([+0-]|-\+))?(?<width>\d+)?(?<position>\d+\$)?(?<precision>\.\d+)?(?<conversion>[%BCESb-iosux]))|(\\%)/: Invalid group
    at Object.<anonymous> (/var/www/website_mobile/node_modules/fast-printf/dist/src/tokenize.js:4:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
