### ISSUE TITLE
Version 1.6.7 doesnt contain /dist/src/printf.js'

### ISSUE THREAD

**Issue by Firaenix** [gajus/fast-printf#7]
Hi,

One of my packages (roarr) updated to use version 1.6.7 of this library and my application has stopped working.

```
Error: Cannot find module '/app/node_modules/fast-printf/dist/src/printf.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:295:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/node_modules/roarr/dist/src/factories/createLogger.js:7:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/app/node_modules/fast-printf/package.json',
  requestPath: 'fast-printf'
```

Also I get a 404 for /dist/src/printf.js on unpkg.
https://unpkg.com/fast-printf@1.6.7/dist/src/printf.js

**Comment by alex-simmons** [comment]
I've had the same issue, for now adding ```"fast-printf": "1.6.5"``` to package.json to use the older version seems to be fine as roarr only requires ^1.6.4

**Comment by vthanghq1** [comment]
I'm facing this issue with version 1.6.7 ... so I downgrade it to 1.6.6

**Comment by marcbachmann** [comment]
Same here. `http-terminator` > `roarr` > `fast-printf` is my dependency tree.
Looks like the module doesn't have any content.
![image](https://user-images.githubusercontent.com/431376/130209013-dbf416a1-e4a7-4a34-b0d2-d92a638697fe.png)

**Comment by geevb** [comment]
We're not using this module directly so downgrading it does not makes sense in our case.

To fix it, we just added 
```
    "resolutions": {
      "fast-printf": "1.6.5"
    },
```

to package.json and the probem went away.

**Comment by ghost** [comment]
same error

**Comment by rdlowrey** [comment]
same issue. working band-aid for now is the same thing @alex-simmons mentioned in https://github.com/gajus/fast-printf/issues/7#issuecomment-902414565

**Comment by gajus** [comment]
Sorry – The build process broke due to a dependency update.

It has been fixed now.
